[tool.poetry]
name = "datalogger"
version = "0.1.0"
description = "Python package for logging data from scientific experiments."
authors = ["Alex Hadley <alexhad6@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/PainterQubits/datalogger"

[tool.poetry.dependencies]
python = "^3.10"
typing-extensions = "^4.7.1"
numpy = "^1.25.2"
xarray = "^2023.7.0"
netcdf4 = "^1.6.4"

[tool.poetry.group.paramdb.dependencies]
paramdb = "^0.9.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
flake8 = "^6.1.0"
pylint = "^2.17.5"
black = "^23.7.0"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"

[tool.mypy]
strict = true

[tool.pylint.basic]
good-names-rgxs = ["^[a-z][a-z0-9]?$"]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
