[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "datalogger"
version = "0.3.0"
description = "Python package for logging data from scientific experiments."
authors = ["Alex Hadley <contact@alexhadley.net>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/PainterQubits/datalogger"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
typing-extensions = "^4.8.0"
numpy = "^1.26.1"
xarray = "^2023.10.1"
netcdf4 = "^1.6.5"
paramdb = {version = "^0.10.0", optional = true}

[tool.poetry.extras]
paramdb = ["paramdb"]

[tool.poetry.group.dev.dependencies]
mypy = "^1.6.1"
flake8 = "^6.1.0"
pylint = "^3.0.2"
black = "^23.10.1"
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
freezegun = "^1.2.2"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
myst-parser = "^2.0.0"
furo = "^2023.9.10"
sphinx-copybutton = "^0.5.2"
jupyter-sphinx = "^0.4.0"
ipykernel = "^6.26.0"
directory-tree = "^0.0.4"
sphinx-autobuild = "^2021.3.14"

[tool.mypy]
strict = true

[tool.pylint.basic]
good-names-rgxs = ["^[a-z][a-z0-9]?$"]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
filterwarnings = [
    # See https://github.com/pydata/xarray/issues/7259
    "ignore:numpy.ndarray size changed",
]
